name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
        # Required for chromium/firefox/webkit
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Execute tests
      - name: Run Playwright tests
        run: npx playwright test

      # Upload test report if failed
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/